### ISSUE TITLE
SQL Error xf_attachment

### ISSUE THREAD

**Issue by sc4t** [mybb/merge-system#192] opened 2016-01-20 09:03 UTC
I have an error with the xenforo converter

MyBB SQL Error
MyBB has experienced an internal SQL error and cannot continue.

SQL Error:
1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM xf_attachment' at line 1
Query:
SELECT FROM xf_attachment
Please contact the MyBB Group for technical support.

**Comment by JN-Jones** [comment] 2016-01-20 10:26
Please use the support forums for support. As said there this is likely a duplicate of #186

**Comment by JN-Jones** [comment] 2016-02-01 14:38
Closing this as no feedback was provided.

**Closed as completed by JN-Jones** 2016-02-01 14:38 UTC
Labels: s:rejected
