### ISSUE TITLE
Error when trying to convert settings SMF 2

### ISSUE THREAD

**Issue by JovanJ** [mybb/merge-system#36] opened 2013-09-30 21:19 UTC
Error:

```
1054 - Unknown column 'variable' in 'where clause'
```

Just noticed this error, I wasn't able to take a look over the code and see what is happening.

**Comment by JordanMussi** [comment] 2014-09-02 18:24
Does this apply to 1.8? As the 1.6 Merge System will receive no more updates keeping a 1.6-specific issue on the tracker is unnecessary.

**Comment by JN-Jones** [comment] 2014-09-09 14:30
I'm not able to reproduce this, the settings table has a column `variable`

**Comment by JN-Jones** [comment] 2014-10-18 22:06
@JovanJ? Otherwise I'll close this.

**Closed as completed** 2014-10-24 12:05 UTC
Labels: s:rejected
