### ISSUE TITLE
string interpolation 0 value bug

### ISSUE THREAD

**Issue by ghost** [mybb/merge-system#190] opened 2015-12-01 07:14 UTC
in /resource/modules/attachments.php, line 288:

`$query = $db->simple_select("posts", "tid", "pid={$converted_data['pid']}");`

When pid = 0 it becomes an empty string on php 5.4.x

**Comment by Stefan-MyBB** [comment] 2015-12-01 09:43
Duplicate of #182?

**Closed as completed** 2015-12-04 09:26 UTC
Labels: s:duplicate
