### ISSUE TITLE
 attachments.php merging error

### ISSUE THREAD

**Issue by JovanJ** [mybb/merge-system#18] opened 2013-09-26 20:27 UTC
From this thread :: http://community.mybb.com/thread-80881.html

If it's fairly common in the Merge System for the merge to stop when it's importing a lot of attachments, then it should be looked into making this system less "susceptible" to this.

http://dev.mybb.com/issues/1288

**Comment by JordanMussi** [comment] 2014-09-02 18:25
Does this apply to 1.8? As the 1.6 Merge System will receive no more updates keeping a 1.6-specific issue on the tracker is unnecessary.

**Comment by JN-Jones** [comment] 2015-06-16 15:11
Duplicate of #23 (don't know why I haven't closed this yet...)

**Closed as completed by JN-Jones** 2015-06-16 15:11 UTC
Labels: s:rejected
